import { resend } from '../../lib/resendClient.js';
import { logger } from '../../utils/logger.js';

const FROM = 'noreply@hdhmarketfrontier.com';
const ADMIN_EMAIL = 'harryhwang37@gmail.com';

export async function sendNotification(
  title: string,
  summary: string,
  editUrl: string,
  date: string,
): Promise<void> {
  logger.info('Sending email notification...');

  const subject = `[HDH Market Frontier] Weekly Market Brief Ready — ${date}`;

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${subject}</title>
</head>
<body style="margin:0;padding:0;background-color:#0F172A;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background-color:#0F172A;padding:40px 0;">
    <tr>
      <td align="center">
        <table width="600" cellpadding="0" cellspacing="0" style="background-color:#1E293B;border-radius:8px;overflow:hidden;max-width:600px;width:100%;">
          <tr>
            <td style="background-color:#1D4ED8;padding:24px 32px;">
              <p style="margin:0;color:#93C5FD;font-size:12px;font-weight:600;letter-spacing:0.1em;text-transform:uppercase;">HDH Market Frontier</p>
              <h1 style="margin:8px 0 0;color:#FFFFFF;font-size:22px;font-weight:700;">Weekly Market Brief is Ready for Review</h1>
            </td>
          </tr>
          <tr>
            <td style="padding:32px;">
              <h2 style="margin:0 0 16px;color:#F1F5F9;font-size:18px;font-weight:600;">${title}</h2>

              <table cellpadding="0" cellspacing="0" style="margin-bottom:24px;">
                <tr>
                  <td style="color:#64748B;font-size:13px;padding-right:16px;">Generated</td>
                  <td style="color:#CBD5E1;font-size:13px;">${new Date().toUTCString()}</td>
                </tr>
                <tr>
                  <td style="color:#64748B;font-size:13px;padding-right:16px;padding-top:8px;">Date</td>
                  <td style="color:#CBD5E1;font-size:13px;padding-top:8px;">${date}</td>
                </tr>
                <tr>
                  <td style="color:#64748B;font-size:13px;padding-right:16px;padding-top:8px;">Status</td>
                  <td style="padding-top:8px;">
                    <span style="display:inline-block;background-color:#FEF3C7;color:#92400E;font-size:12px;font-weight:600;padding:2px 10px;border-radius:12px;">Draft — Not Published</span>
                  </td>
                </tr>
              </table>

              <p style="margin:0 0 24px;color:#94A3B8;font-size:15px;line-height:1.6;">${summary}</p>

              <table cellpadding="0" cellspacing="0">
                <tr>
                  <td style="border-radius:6px;background-color:#2563EB;">
                    <a href="${editUrl}" style="display:inline-block;padding:14px 28px;color:#FFFFFF;font-size:15px;font-weight:600;text-decoration:none;border-radius:6px;">Review &amp; Edit Article →</a>
                  </td>
                </tr>
              </table>

              <p style="margin:24px 0 0;color:#475569;font-size:13px;">
                Or copy this link: <a href="${editUrl}" style="color:#60A5FA;word-break:break-all;">${editUrl}</a>
              </p>
            </td>
          </tr>
          <tr>
            <td style="border-top:1px solid #334155;padding:20px 32px;">
              <p style="margin:0;color:#475569;font-size:12px;line-height:1.5;">
                This email was auto-generated by the HDH Market Frontier weekly briefing pipeline.<br />
                The article is saved as a draft and requires your review before publishing.
              </p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;

  const { error } = await resend.emails.send({
    from: FROM,
    to: ADMIN_EMAIL,
    subject,
    html,
  });

  if (error) {
    throw new Error(`Email send failed: ${JSON.stringify(error)}`);
  }

  logger.info('Email notification sent.');
}
